### ISSUE TITLE
Typo and issue with wording in the M6 Javascript Exam

### ISSUE THREAD

**Issue by caius-faustus** [ConsenSys-Academy/basic-training#15]
For Question three there is an error with a missing beginning parenthesis, this error is not supposed to happen as the correct answer is how the code would work sans typo. Question one the wording seems weird and I couldn't decide if I was supposed to select from the most popular of the primitive data types that were listed. Question eight I'm unsure of, I think that the standard only specifies 3 states for a promise, though it does mention settled descriptively it doesn't indicate that settled is a state, see http://262.ecma-international.org/11.0/#sec-promise-objects

Sorry if this isn't in a correct format or doesn't actually belong here as an issue, wasn't sure where to provide feedback and am not familiar with using github.

![Question_3_M6](https://user-images.githubusercontent.com/85305581/120713136-5a979280-c476-11eb-8628-ec41e233d837.png)
![Question_8_M6](https://user-images.githubusercontent.com/85305581/120713140-5b302900-c476-11eb-9ee0-b4ddccaa8b57.png)
![Question_1_M6](https://user-images.githubusercontent.com/85305581/120713145-5b302900-c476-11eb-9d99-fdf67ef6102e.png)

**Comment by ConsenSys-Academy** [comment]
Thank you for catching this! It's in the Content Management System, we're looking into it now and will get back to you!

**Comment by Robbiekruszynski** [comment]
**Question 1:**

Has been refactored, thank you for bringing this up. 

New version: 
Please select all of the javascript primitive types from the options below?
(hint: remember a primitive can only hold a single value!)


**Question 3**
Thank you for catching that missing (

the correct code now reads as the following

```
const quiz = {
course: "ConsenSys Academy",  
year: 2021,
getCourse: function() {
console.log(this.course);
  }
}
 quiz.getCourse();
```


**Question 8:** 
This one was tricky since there are some floating conversations on the 3 vs 4 states of a promise but I do agree and this has been reworked to 3 opposed to 4.

Rework: 
Select the three main states of a promise in javascript


**Note:**
A promise is an object which can be returned synchronously from an asynchronous function. It will be in one of 3 possible states:

Fulfilled: onFulfilled() will be called (e.g., resolve() was called)
Rejected: onRejected() will be called (e.g., reject() was called)
Pending: not yet fulfilled or rejected

A promise is settled if it’s not pending (it has been resolved or rejected). Sometimes people use resolved and settled to mean the same thing: not pending.


Thank you again for bringing this up @caius-faustus. Super helpful.

**Comment by caius-faustus** [comment]
Glad I could help.
